version: 2.1

orbs:
  docker: circleci/docker@2.6.0
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    steps:
      - checkout
      - docker/check
      - docker/publish:
          deploy: true
          registry: docker.io 
          image: mbuse0/hira-web
          tag: ${CIRCLE_SHA1}
workflows:
  commit:
    jobs:
      - build
