version: 2.1

orbs:
  docker: circleci/docker@2.6.0
executors:
  arm:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
jobs:
  publish:
    executor: arm
    steps:
      - checkout
      - docker/check
      - docker/build:
          image: mbuse0/home-web
          tag: ${CIRCLE_SHA1}
      - docker/push:
          registry: docker.io 
          image: mbuse0/home-web
          tag: ${CIRCLE_SHA1}
workflows:
  build:
    jobs:
      - publish
