version: 2.1

machine:
  image: ubuntu-2004:current
resource_class: arm.medium
orbs:
  docker: circleci/docker@2.6.0
workflows:
  build:
    jobs:
      - docker/publish:
          deploy: true
          registry: docker.io 
          image: mbuse0/hira-web
          tag: ${CIRCLE_SHA1}
